### ISSUE TITLE
Database Diagram

### ISSUE THREAD

**Issue by camerican** [Smergel/twitterTrender#1]
Sketch a database diagram including tables, their fields, and the entity relationships within the system.

**Comment by webolton** [comment]
User

user_name:string
email:string
password_hash:string
password_salt:string
admin:boolean

Location

city_name:string
woeid:integer
user_id:integer

Users have many Locations
Locations have one User

**Comment by camerican** [comment]
![image](https://cloud.githubusercontent.com/assets/2566680/9065412/47191ca4-3a9f-11e5-959a-00a7d3567069.png)
